import type { Metadata } from "next";
import { Cairo, Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./components/header/Header";
import MainHeader from "./components/header/MainHeader";

const inter = Inter({ subsets: ["latin"] });
const cairo = Cairo({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="ar" className="dark">
      <body className={cairo.className}>
        <Providers>
          <MainHeader />
          <main className="pt-[66px] dark:bg-zinc-900 page-height">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
